package com.example.personallearningapp.activities.Task;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.AppCompatButton;

import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.view.View;
import android.widget.TextView;
import android.widget.Toast;

import com.example.personallearningapp.R;
import com.example.personallearningapp.activities.Quiz.QuizActivity;
import com.example.personallearningapp.models.Quiz;
import com.example.personallearningapp.models.User;
import com.example.personallearningapp.models.UserInterest;
import com.example.personallearningapp.utils.QuizFetchListener;
import com.google.common.util.concurrent.FutureCallback;
import com.google.common.util.concurrent.Futures;
import com.google.common.util.concurrent.ListenableFuture;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class TaskActivity extends AppCompatActivity implements QuizFetchListener, View.OnClickListener {
    User user;
    TextView name_text;
    TextView taskTitle;
    TextView taskDescription;
    AppCompatButton startTaskButton;
    TaskViewModel viewModel;
    Quiz quizPersisted;
    List<UserInterest> userInterestList;
    List<String> formattedUserInterestList = new ArrayList<>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_task);

        viewModel = new TaskViewModel(this);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            user = getIntent().getSerializableExtra("USER", User.class);
        }

        name_text = findViewById(R.id.name_text);
        String name = user.getFirstName() + " " + user.getLastName();
        name_text.setText(name);

        taskTitle = findViewById(R.id.task_title);
        taskDescription = findViewById(R.id.task_description);
        startTaskButton = findViewById(R.id.start_task_button);

        getUserInterests();

        startTaskButton.setOnClickListener(this);
    }

    private void getUserInterests() {
        ListenableFuture<List<UserInterest>> userInterestsFuture = viewModel.getAllByUsername(user.getUsername());
        Futures.addCallback(userInterestsFuture, new FutureCallback<List<UserInterest>>() {
            @Override
            public void onSuccess(List<UserInterest> result) {
                userInterestList = result;
                formatUserInterestList(userInterestList);
                Random random = new Random();
                int randomIndex = random.nextInt(formattedUserInterestList.size());
                viewModel.setQuizFetchListener(TaskActivity.this);
                viewModel.fetchQuizData(formattedUserInterestList.get(randomIndex));
            }

            @Override
            public void onFailure(Throwable t) {
                Toast.makeText(TaskActivity.this, "Failed to get user interests", Toast.LENGTH_SHORT).show();
            }
        }, getMainExecutor());
    }

    private void formatUserInterestList(List<UserInterest> userInterestList) {
        if(userInterestList != null) {
            for (UserInterest interest : userInterestList) {
                String formattedInterest = interest.getInterest().replaceAll(" ", "%20");
                formattedUserInterestList.add(formattedInterest);
            }
        }
    }

    @Override
    public void onQuizFetched(Quiz quiz) {
        quizPersisted = quiz;
        String title = quizPersisted.getTopic() + " quiz";
        String description = title + " generated by Llama2 large language model";
        taskTitle.setText(title);
        taskDescription.setText(description);
        startTaskButton.setText("Start");
    }

    @Override
    public void onClick(View v) {
        AppCompatButton button = (AppCompatButton) v;
        String buttonText = button.getText().toString();
        String quizTitle = "";
        String quizDescription = "";
        if(quizPersisted != null) {
            quizTitle = quizPersisted.getTopic() + " quiz";
            quizDescription = quizTitle + " generated by Llama2 large language model";
        } else {
            Toast.makeText(this, "Fetching quiz", Toast.LENGTH_SHORT).show();
        }

        if (buttonText.equals("Start")) {
            Intent intent = new Intent(TaskActivity.this, QuizActivity.class);
            intent.putExtra("QUIZ", quizPersisted);
            intent.putExtra("TITLE", quizTitle);
            intent.putExtra("DESCRIPTION", quizDescription);
            intent.putExtra("USER", user);
            startActivity(intent);
        }
    }
}